---
driver:
  name: vagrant

provisioner:
  name: chef_solo

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos-7.1
  #- name: npalm/mint17-amd64-cinnamon

suites:
  - name: default
    run_list:
      - recipe[chefdk_gs::default]
    attributes:
