from building_tests import BuildingBlockTester, BuildingLayerTester, BuildingTester
from lamppost_tests import LampPostTester
from well_tests import WellTester
from small_house_tests import SmallHouseV1Tester
from small_house_tests import SmallHouseV2Tester
from small_house_tests import SmallHouseV3Tester
